### PR TITLE
Issue: 1

### PR DESCRIPTION
**Pull request by KBVijayVarma**
Issue: 1

Added my User Name and Colab Link for Task-1 in the Submission Folder

### CODE REVIEW

**Comment by parth1007** [comment]
Please give a check for duplicates and you have to deal with "example_very_unclear".

**Comment by KBVijayVarma** [comment]
Ok will check and remove the Duplicates. 
Should I remove the 'example_very_unclear' = True Rows in the Dataframe?. (I thought they would be removed in a later stage.)
Updating the Colab Notebook is enough right?
Comment for any more changes.

**Comment by parth1007** [comment]
You need to remove those rows. And yes, just update the notebook. No need for new PR. 

Comment once done.

**Comment by KBVijayVarma** [comment]
Updated the Notebook with required Changes.

**Pull request merged**
